### PR TITLE
fix: support for Timer registers in ATMEGA128/L

### PR DESCRIPTION
**Pull request by camiloVargasTechnaid**
Actual  ->  Adding for ATMEGA128
---
TIMSK0  ->  TIMSK (register)
OCIE0A  ->  OCIE0 (register_bit)
OCR0A   ->  OCR0 (register)

### CODE REVIEW

**Comment by greiman** [comment]
I am no longer supporting this library.

**Comment by camiloVargasTechnaid** [comment]
I'm sorry for that, I am using ChNil in PlatformIO when I want some nice RTOS into ATMega products, add some support for ATMega128 will be a great idea to continue with its use.

**Comment by greiman** [comment]
There is not enough interest to be worth the time to update this library.  This is version 2.0.0 of nill which is very old so I don't want to patch it.

The current version is 4.1.2.  It would require a lot of effort to port it and test it.

**Comment by camiloVargasTechnaid** [comment]
I completely understand you! (too old version)

Thank you for all the support and I wish you the best for all your projects!

**Pull request closed without merging**
